CREATE TABLE IF NOT EXISTS t_entry (
	id INT(11) NOT NULL AUTO_INCREMENT,
	created DATETIME DEFAULT NULL,
	title VARCHAR(255) DEFAULT NULL,
	content TEXT DEFAULT NULL,
	authore VARCHAR(50) DEFAULT NULL,
	comments INT(12) DEFAULT NULL,
	idUser INT(12) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;