CREATE TABLE IF NOT EXISTS t_user (
	id INT(11) NOT NULL AUTO_INCREMENT,
	login VARCHAR(50) DEFAULT NULL,
	password VARCHAR(255) DEFAULT NULL,
	email VARCHAR(100) DEFAULT NULL,
	fullname VARCHAR(50) DEFAULT NULL,
	street VARCHAR(255) DEFAULT NULL,
	postcode VARCHAR(50) DEFAULT NULL,
	place VARCHAR(50) DEFAULT NULL,
	created DATETIME DEFAULT NULL,
	createdBy VARCHAR(50) DEFAULT NULL,
	updated DATETIME DEFAULT NULL,
	updatedBy VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;